version: '3.1'

services:

  redis:
    restart: always
    image: redis:latest
    ports:
      - 6379
    volumes:
      - redisdata:/data

  links_api:
    image: rest_api
    build: ./
#    command: gunicorn time_links.wsgi:application --bind 0.0.0.0:8000
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/links_api
    env_file:
      - ./.env.local
    ports:
      - 8000:8000
    depends_on:
      - redis


volumes:
  redisdata:
